### ISSUE TITLE
Hardcoded realmd in model.php

### ISSUE THREAD

**Issue by Daxiongmao87** [vcorbuleanu/cmangos-website#3]
https://github.com/vcorbuleanu/cmangos-website/blob/0b8baa2f0c3f6ac46cedb3c067816fc4a3664200/framework/core/model.php#L13C192-L13C199

this line has multiple instances of hardcoded 'realmd' database, which means it ignores config.php values.  This affects specifically logging in

**Comment by vcorbuleanu** [comment]
Fixed.
Thanks for pointing it out, and sorry it took so long to fix. I've been quite busy as of late.
